import type { ApexAction } from '../apexAction';

// Generates Anonymous Apex scripts that replay captured calls.
// Complex params are emitted as (TODO_Type) JSON.deserialize('<json>', TODO_Type.class)
// because the wire capture carries values, not Apex type names.

const LARGE_LITERAL_CHARS = 100_000;
const LARGE_SCRIPT_CHARS = 1_000_000;

const UI_RECORD_API_SUPPORTED = new Set([
  'createRecord',
  'updateRecord',
  'deleteRecord',
  'getRecord',
  'getRecordWithFields',
  'getRecords',
]);

export function canGenerateAnonApex(action: ApexAction): boolean {
  switch (action.callType) {
    case 'aura':
    case 'community':
    case 'vfremoting':
    case 'apexrest':
      return true;
    case 'uirecordapi':
      return UI_RECORD_API_SUPPORTED.has(action.method);
    default:
      return false;
  }
}

// Escape order matters: backslashes first, then quotes, then control chars.
function apexStringLiteral(s: string): string {
  return "'" + s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t') + "'";
}

// Compact stringify guarantees no literal newlines inside the Apex string.
function apexJsonLiteral(value: unknown): string {
  return apexStringLiteral(JSON.stringify(value));
}

function sanitizeIdentifier(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z]/.test(cleaned) ? cleaned : 'p' + cleaned;
}

function pascalCase(name: string): string {
  const id = sanitizeIdentifier(name);
  return id.charAt(0).toUpperCase() + id.slice(1);
}

interface RenderedParam {
  decls: string[];
  argExpr: string;
}

// varPrefix distinguishes calls within a boxcar script ('' for single calls).
function renderParam(name: string, value: unknown, varPrefix: string): RenderedParam {
  const varName = `p${varPrefix}_${sanitizeIdentifier(name)}`;
  if (value === null || value === undefined) {
    return { decls: [], argExpr: `null /* ${name} */` };
  }
  if (typeof value === 'string') {
    return { decls: [`String ${varName} = ${apexStringLiteral(value)};`], argExpr: varName };
  }
  if (typeof value === 'boolean') {
    return { decls: [`Boolean ${varName} = ${value};`], argExpr: varName };
  }
  if (typeof value === 'number') {
    if (Number.isInteger(value)) {
      const fits32 = Math.abs(value) < 2 ** 31;
      return {
        decls: [fits32 ? `Integer ${varName} = ${value};` : `Long ${varName} = ${value}L;`],
        argExpr: varName,
      };
    }
    return { decls: [`Decimal ${varName} = ${value};`], argExpr: varName };
  }
  // Object or array: deserialize with a placeholder type.
  const todoType = `TODO_${pascalCase(name)}Type`;
  const json = apexJsonLiteral(value);
  const decls = [
    `// TODO: replace ${todoType} with the real Apex type of parameter "${name}"`,
    `// (untyped alternative: (Map<String,Object>) JSON.deserializeUntyped(...) / (List<Object>) for arrays)`,
  ];
  if (json.length > LARGE_LITERAL_CHARS) {
    decls.push(`// WARNING: large payload (~${Math.round(json.length / 1024)} KB). Anonymous Apex compiles up to ~6M chars, but IDEs may struggle; consider a StaticResource.`);
  }
  decls.push(`${todoType} ${varName} = (${todoType}) JSON.deserialize(${json}, ${todoType}.class);`);
  return { decls, argExpr: varName };
}

const CALL_TYPE_LABELS: Record<string, string> = {
  aura: 'Aura @AuraEnabled',
  community: 'Experience Cloud @AuraEnabled (webruntime)',
  vfremoting: 'Visualforce Remoting @RemoteAction',
  uirecordapi: 'uiRecordApi (lightning/uiRecordApi)',
  apexrest: 'Apex REST (@RestResource)',
};

function headerComment(action: ApexAction): string[] {
  const lines = [
    '/*',
    ` * Generated by Apex Inspector on ${new Date().toISOString()}`,
    ` * Source: ${action.network.url}`,
    ` * Captured: ${new Date(action.timestamp).toISOString()} | Latency: ${action.latency ?? '?'} ms | Type: ${CALL_TYPE_LABELS[action.callType] ?? action.callType}`,
  ];
  if (action.error) {
    lines.push(` * Original call ERRORED: ${String(action.error).split('\n')[0]}`);
  }
  lines.push(' */');
  return lines;
}

// Aura wire params mix user args with call metadata; community requests are pure args.
const AURA_META_KEYS = new Set(['classname', 'className', 'method', 'methodName', 'namespace', 'cacheable', 'isContinuation']);

function extractAuraUserParams(action: ApexAction): Record<string, unknown> {
  const req = action.request || {};
  if (action.callType === 'community') return req;
  const inner = req.params;
  if (inner && typeof inner === 'object' && !Array.isArray(inner)) {
    return inner as Record<string, unknown>;
  }
  const rest: Record<string, unknown> = {};
  Object.entries(req).forEach(([k, v]) => {
    if (!AURA_META_KEYS.has(k)) rest[k] = v;
  });
  return rest;
}

function resolveClassName(action: ApexAction): { className: string; todoLines: string[] } {
  if (action.context && action.context.needsMapping) {
    return {
      className: 'TODO_ApexClass',
      todoLines: [
        `// TODO: class name is obfuscated by Experience Cloud (${String(action.context.originalClassName ?? action.apexClass)}).`,
        `// Configure "Apex Class Mappings JSON" in extension settings, or replace TODO_ApexClass manually.`,
      ],
    };
  }
  return { className: action.apexClass, todoLines: [] };
}

function generateNamedParamCall(action: ApexAction, varPrefix: string, resultVar: string): string[] {
  const params = extractAuraUserParams(action);
  const entries = Object.entries(params);
  const { className, todoLines } = resolveClassName(action);
  const lines: string[] = [...todoLines];

  if (entries.length > 1) {
    lines.push(
      '// NOTE: @AuraEnabled methods receive NAMED parameters over the wire; Apex calls are',
      '// POSITIONAL. Argument order below follows the captured JSON key order and may not',
      '// match the method signature - verify against the class before running.'
    );
  }

  const args: string[] = [];
  entries.forEach(([name, value]) => {
    const rendered = renderParam(name, value, varPrefix);
    lines.push(...rendered.decls);
    args.push(rendered.argExpr === `null /* ${name} */` ? rendered.argExpr : `${rendered.argExpr} /* ${name} */`);
  });
  if (entries.length === 0) {
    lines.push('// NOTE: no request parameters were captured');
  }

  lines.push(
    '',
    `Object ${resultVar} = ${className}.${action.method}(${args.join(', ')});`,
    `System.debug(JSON.serializePretty(${resultVar}));`
  );
  return lines;
}

function generateVfRemotingCall(action: ApexAction, varPrefix: string, resultVar: string): string[] {
  const data: unknown[] = Array.isArray(action.request) ? (action.request as unknown[]) : [];
  const lines: string[] = ['// @RemoteAction methods are static; argument order matches the captured array exactly.'];
  const args: string[] = [];
  data.forEach((value, idx) => {
    const rendered = renderParam(`arg${idx + 1}`, value, varPrefix);
    lines.push(...rendered.decls);
    args.push(rendered.argExpr);
  });
  if (data.length === 0) {
    lines.push('// NOTE: no request parameters were captured');
  }
  lines.push(
    '',
    `Object ${resultVar} = ${action.apexClass}.${action.method}(${args.join(', ')});`,
    `System.debug(JSON.serializePretty(${resultVar}));`
  );
  return lines;
}

function generateUiRecordApiCall(action: ApexAction, varPrefix: string): string[] {
  const req = action.request || {};
  const recordInput = (req.recordInput && typeof req.recordInput === 'object' ? req.recordInput : {}) as Record<string, unknown>;
  const fieldsObj = (recordInput.fields && typeof recordInput.fields === 'object' ? recordInput.fields : {}) as Record<string, unknown>;
  const recVar = `rec${varPrefix || ''}`;

  const putLines = (target: string): string[] =>
    Object.entries(fieldsObj)
      .filter(([field]) => field !== 'Id')
      .map(([field, value]) => {
        if (value === null || value === undefined) return `${target}.put('${field}', null);`;
        if (typeof value === 'object') return `// TODO: compound field "${field}" skipped - set its sub-fields individually`;
        if (typeof value === 'string') return `${target}.put('${field}', ${apexStringLiteral(value)});`;
        return `${target}.put('${field}', ${value});`;
      });

  switch (action.method) {
    case 'createRecord': {
      const apiName = String(recordInput.apiName ?? req.apiName ?? 'TODO_ObjectApiName');
      return [
        `SObject ${recVar} = Schema.getGlobalDescribe().get('${apiName}').newSObject();`,
        ...putLines(recVar),
        `insert ${recVar};`,
        `System.debug('Created: ' + ${recVar}.Id);`,
      ];
    }
    case 'updateRecord': {
      const recordId = String(fieldsObj.Id ?? req.recordId ?? 'TODO_RecordId');
      return [
        `Id recordId${varPrefix} = '${recordId}';`,
        `SObject ${recVar} = recordId${varPrefix}.getSObjectType().newSObject(recordId${varPrefix});`,
        ...putLines(recVar),
        `update ${recVar};`,
        `System.debug('Updated: ' + recordId${varPrefix});`,
      ];
    }
    case 'deleteRecord': {
      const recordId = String(req.recordId ?? 'TODO_RecordId');
      return [
        `Id recordId${varPrefix} = '${recordId}';`,
        `Database.delete(recordId${varPrefix});`,
        `System.debug('Deleted: ' + recordId${varPrefix});`,
      ];
    }
    default: {
      // getRecord / getRecordWithFields / getRecords - fields arrive qualified as Object.Field
      const recordId = String(req.recordId ?? 'TODO_RecordId');
      const fields = Array.isArray(req.fields) ? (req.fields as string[]) : [];
      const objectName = fields.length > 0 && fields[0].includes('.')
        ? fields[0].split('.')[0]
        : 'TODO_ObjectApiName';
      const lines = [`Id recordId${varPrefix} = '${recordId}';`];
      if (fields.length > 0) {
        const bareFields = [...new Set(fields.map(f => f.split('.').slice(1).join('.') || f))];
        lines.push(
          `List<SObject> recs${varPrefix} = Database.query(`,
          `  'SELECT ${bareFields.join(', ')} FROM ${objectName} WHERE Id = :recordId${varPrefix}'`,
          `);`
        );
      } else {
        const layoutType = req.layoutType ? String(req.layoutType) : null;
        lines.push(
          `// NOTE: original call was layout-driven${layoutType ? ` (layoutType=${layoutType})` : ''}; FIELDS(ALL) approximates it (max 200 rows).`,
          `List<SObject> recs${varPrefix} = Database.query(`,
          `  'SELECT FIELDS(ALL) FROM ${objectName} WHERE Id = :recordId${varPrefix} LIMIT 1'`,
          `);`
        );
      }
      lines.push(`System.debug(JSON.serializePretty(recs${varPrefix}));`);
      return lines;
    }
  }
}

const VERB_ANNOTATIONS: Record<string, string> = {
  GET: '@HttpGet',
  POST: '@HttpPost',
  PATCH: '@HttpPatch',
  PUT: '@HttpPut',
  DELETE: '@HttpDelete',
};

function generateApexRestCall(action: ApexAction, varPrefix: string): string[] {
  const ctx = action.context || {};
  const restPath = String(ctx.restPath ?? '/');
  const httpMethod = String(ctx.httpMethod ?? action.method ?? 'GET').toUpperCase();
  const queryParams = (ctx.queryParams && typeof ctx.queryParams === 'object' ? ctx.queryParams : {}) as Record<string, string>;
  const bodyText = typeof ctx.requestBodyText === 'string' ? ctx.requestBodyText : null;
  const contentType = typeof ctx.requestContentType === 'string' ? ctx.requestContentType : null;
  const reqVar = `req${varPrefix}`;
  const annotation = VERB_ANNOTATIONS[httpMethod] || '@HttpGet';

  const lines = [
    `RestRequest ${reqVar} = new RestRequest();`,
    `${reqVar}.requestURI = '/services/apexrest${restPath}';`,
    `${reqVar}.httpMethod = '${httpMethod}';`,
  ];
  if (contentType) {
    lines.push(`${reqVar}.addHeader('Content-Type', ${apexStringLiteral(contentType)});`);
  }
  Object.entries(queryParams).forEach(([k, v]) => {
    lines.push(`${reqVar}.params.put(${apexStringLiteral(k)}, ${apexStringLiteral(v)});`);
  });
  if (bodyText) {
    if (bodyText.length > LARGE_LITERAL_CHARS) {
      lines.push(`// WARNING: large body (~${Math.round(bodyText.length / 1024)} KB)`);
    }
    lines.push(`${reqVar}.requestBody = Blob.valueOf(${apexStringLiteral(bodyText)});`);
  }
  lines.push(
    `RestContext.request = ${reqVar};`,
    `RestContext.response = new RestResponse();`,
    '',
    `// TODO: replace with the @RestResource(urlMapping='${restPath.replace(/^\/([^/]+).*/, '/$1')}/*') class and its`,
    `// ${annotation}-annotated method. Handler methods in this pattern take no arguments;`,
    `// URI, body, and params are read from RestContext inside the handler.`,
    `TODO_RestResourceClass.TODO_${httpMethod.toLowerCase()}Handler();`,
    '',
    `System.debug(RestContext.response.statusCode);`,
    `System.debug(RestContext.response.responseBody != null`,
    `  ? RestContext.response.responseBody.toString() : '(no body)');`
  );
  return lines;
}

function generateBody(action: ApexAction, varPrefix: string, resultVar: string): string[] {
  switch (action.callType) {
    case 'aura':
    case 'community':
      return generateNamedParamCall(action, varPrefix, resultVar);
    case 'vfremoting':
      return generateVfRemotingCall(action, varPrefix, resultVar);
    case 'uirecordapi':
      return generateUiRecordApiCall(action, varPrefix);
    case 'apexrest':
      return generateApexRestCall(action, varPrefix);
    default:
      return [`// Call type "${action.callType}" cannot be exported to Anonymous Apex.`];
  }
}

function withSizeWarning(script: string): string {
  if (script.length > LARGE_SCRIPT_CHARS) {
    return `// WARNING: this script is ~${Math.round(script.length / 1024)} KB; execution tools may reject very large Anonymous Apex.\n` + script;
  }
  return script;
}

export function generateAnonApex(action: ApexAction): string {
  const lines = [...headerComment(action), '', ...generateBody(action, '', 'result')];
  return withSizeWarning(lines.join('\n'));
}

export function generateBoxcarAnonApex(actions: ApexAction[]): string {
  if (actions.length === 0) return '// No calls to export.';
  if (actions.length === 1) return generateAnonApex(actions[0]);

  const lines = [
    '/*',
    ` * Generated by Apex Inspector on ${new Date().toISOString()}`,
    ` * Boxcarred request: ${actions.length} calls replayed in capture order`,
    ` * Source: ${actions[0].network.url}`,
    ' */',
  ];
  actions.forEach((action, idx) => {
    const n = idx + 1;
    lines.push('', `// ---- Call ${n}/${actions.length}: ${action.apexClass}.${action.method} ----`);
    if (action.error) {
      lines.push(`// Original call ERRORED: ${String(action.error).split('\n')[0]}`);
    }
    if (canGenerateAnonApex(action)) {
      lines.push(...generateBody(action, String(n), `result${n}`));
    } else {
      lines.push(`// Skipped: ${action.callType} calls cannot be exported to Anonymous Apex.`);
    }
  });
  return withSizeWarning(lines.join('\n'));
}
